### ISSUE TITLE
Script availability of the paper 

### ISSUE THREAD

**Issue by csaybar** [brazil-data-cube/compare-cloud-masks#1]
Hi everyone!

Nice work in **Comparison of Cloud Cover Detection Algorithms on Sentinel–2 Images of the Amazon Tropical Forest**. It is a really helpful and complete article for cloud detection practitioners.  I was wondering if scripts used to comparate the performance of cloud detection algorithms are going to be released.

**Comment by albhasan** [comment]
Good afternoon,

The scripts for comparing cloud detection algorithms are being adapted before uploading them here. The preliminary versions are available at:

https://github.com/albhasan/clouds

Bests

**Comment by csaybar** [comment]
Thanks! :)
